services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - /app/target
      - .:/app
    env_file:
      - .env
    command: sh
    tty: true
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
